[workspace]
members = ["tests", "contracts/selection", "contracts/checkpoint", "contracts/common/protocol", "contracts/common/secp256k1"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
